// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CreateStoreUsecase is an autogenerated mock type for the CreateStoreUsecase type
type CreateStoreUsecase struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, name, description, CategoryID, externalID, tags, lat, lng
func (_m *CreateStoreUsecase) Add(ctx context.Context, name string, description string, CategoryID string, externalID string, tags []string, lat float64, lng float64) error {
	ret := _m.Called(ctx, name, description, CategoryID, externalID, tags, lat, lng)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string, float64, float64) error); ok {
		r0 = rf(ctx, name, description, CategoryID, externalID, tags, lat, lng)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
