// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/EdlanioJ/kbu-store/domain"
	mock "github.com/stretchr/testify/mock"
)

// CreateAccountRepository is an autogenerated mock type for the CreateAccountRepository type
type CreateAccountRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, account
func (_m *CreateAccountRepository) Add(ctx context.Context, account *domain.Account) error {
	ret := _m.Called(ctx, account)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
