// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CreateCategoryUsecase is an autogenerated mock type for the CreateCategoryUsecase type
type CreateCategoryUsecase struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, name
func (_m *CreateCategoryUsecase) Add(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
