// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteAccountRepository is an autogenerated mock type for the DeleteAccountRepository type
type DeleteAccountRepository struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, id
func (_m *DeleteAccountRepository) Exec(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
