// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/EdlanioJ/kbu-store/domain"
	mock "github.com/stretchr/testify/mock"
)

// FetchStoreByCloseLocationUsecase is an autogenerated mock type for the FetchStoreByCloseLocationUsecase type
type FetchStoreByCloseLocationUsecase struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, lat, lng, distance, status, limit, page, sort
func (_m *FetchStoreByCloseLocationUsecase) Exec(ctx context.Context, lat float64, lng float64, distance int, status string, limit int, page int, sort string) ([]*domain.Store, int64, error) {
	ret := _m.Called(ctx, lat, lng, distance, status, limit, page, sort)

	var r0 []*domain.Store
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, int, string, int, int, string) []*domain.Store); ok {
		r0 = rf(ctx, lat, lng, distance, status, limit, page, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Store)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, int, string, int, int, string) int64); ok {
		r1 = rf(ctx, lat, lng, distance, status, limit, page, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, float64, float64, int, string, int, int, string) error); ok {
		r2 = rf(ctx, lat, lng, distance, status, limit, page, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
