// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/EdlanioJ/kbu-store/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetAccountByIDRepository is an autogenerated mock type for the GetAccountByIDRepository type
type GetAccountByIDRepository struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, id
func (_m *GetAccountByIDRepository) Exec(ctx context.Context, id string) (*domain.Account, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Account
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
