// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/EdlanioJ/kbu-store/domain"
	mock "github.com/stretchr/testify/mock"
)

// GetStoreByOwnerUsecase is an autogenerated mock type for the GetStoreByOwnerUsecase type
type GetStoreByOwnerUsecase struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, id, externalID
func (_m *GetStoreByOwnerUsecase) Exec(ctx context.Context, id string, externalID string) (*domain.Store, error) {
	ret := _m.Called(ctx, id, externalID)

	var r0 *domain.Store
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Store); ok {
		r0 = rf(ctx, id, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
