// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MessengerProducer is an autogenerated mock type for the MessengerProducer type
type MessengerProducer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MessengerProducer) Close() {
	_m.Called()
}

// Publish provides a mock function with given fields: ctx, msg, topic
func (_m *MessengerProducer) Publish(ctx context.Context, msg string, topic string) error {
	ret := _m.Called(ctx, msg, topic)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, msg, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
