// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/EdlanioJ/kbu-store/domain"
	mock "github.com/stretchr/testify/mock"
)

// UpdateStoreUsecase is an autogenerated mock type for the UpdateStoreUsecase type
type UpdateStoreUsecase struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, store
func (_m *UpdateStoreUsecase) Exec(ctx context.Context, store *domain.Store) error {
	ret := _m.Called(ctx, store)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Store) error); ok {
		r0 = rf(ctx, store)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
