// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/EdlanioJ/kbu-store/domain"
	mock "github.com/stretchr/testify/mock"
)

// UpdateAccountRepository is an autogenerated mock type for the UpdateAccountRepository type
type UpdateAccountRepository struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, account
func (_m *UpdateAccountRepository) Exec(ctx context.Context, account *domain.Account) error {
	ret := _m.Called(ctx, account)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
