FROM golang:1.16 as builder

WORKDIR /go/src
COPY . .

ENV PATH="/go/bin:${PATH}"

RUN make env
RUN make build

FROM scratch

WORKDIR /app

COPY --from=builder ./go/src/kbu-store ./
COPY --from=builder ./go/src/app.env ./

ENTRYPOINT ["./kbu-store"]