version: '3'

services:
  app:
    container_name: kbu-store
    build: .
    ports:
      - '3330:3330'
      - '3333:3333'
      - '50051:50051'
    volumes:
      - .:/go/src/
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - db
  db:
    container_name: kbu-db
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .docker/.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kbu_store
    ports:
      - '25432:5432'
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes: 
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    depends_on:
      - prometheus