basePath: /api/v1
definitions:
  domain.Store:
    properties:
      account_id:
        type: string
      category_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      image:
        type: string
      lat:
        type: number
      lng:
        type: number
      name:
        type: string
      status:
        type: string
      tags:
        items:
          type: string
        type: array
      user_id:
        type: string
    type: object
  handler.CreateStoreRequest:
    properties:
      category_id:
        type: string
      description:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
      tags:
        items:
          type: string
        type: array
      user_id:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      msg:
        type: string
    type: object
  handler.UpdateStoreRequest:
    properties:
      category_id:
        type: string
      description:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
info:
  contact:
    email: edlanioj@gmail.com
    name: Edlâneo Manuel
  description: This is a sample swagger for KBU Store
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: KBU Store API
  version: 2.0.0
paths:
  /stores:
    get:
      consumes:
      - application/json
      description: Get list of stores
      parameters:
      - default: 1
        description: Page
        in: query
        name: page
        type: integer
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - default: created_at DESC
        description: Sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Store'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Index store
      tags:
      - stores
    post:
      consumes:
      - application/json
      description: Create new store
      parameters:
      - description: Create store
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/handler.CreateStoreRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create store
      tags:
      - stores
  /stores/{id}:
    delete:
      consumes:
      - application/json
      description: Delete one stores
      parameters:
      - description: store ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Delete stores
      tags:
      - stores
    get:
      consumes:
      - application/json
      description: Get a stores by id
      parameters:
      - description: store ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Store'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get stores
      tags:
      - stores
    patch:
      consumes:
      - application/json
      description: Uptate a stores
      parameters:
      - description: store ID
        in: path
        name: id
        required: true
        type: string
      - description: Create store
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateStoreRequest'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Update store
      tags:
      - stores
  /stores/{id}/activate:
    patch:
      consumes:
      - application/json
      description: Activate a stores
      parameters:
      - description: store ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Activate stores
      tags:
      - stores
  /stores/{id}/block:
    patch:
      consumes:
      - application/json
      description: Block a stores
      parameters:
      - description: store ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Block stores
      tags:
      - stores
  /stores/{id}/disable:
    patch:
      consumes:
      - application/json
      description: Disable a stores
      parameters:
      - description: store ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Disable stores
      tags:
      - stores
swagger: "2.0"
